spring:
  datasource:
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 3
    url: jdbc:postgresql://chunee.db.elephantsql.com/ngxclgub
    username: ngxclgub
    password: cCGKdjTtCKQILWD5CKhx3aEkLID_t_km
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect